package agh.ics.oop.model.Config;

public enum Parameter {
    MAP_WIDTH,
    MAP_HEIGHT,
    MAP_TYPE,
    MUTATION_TYPE,
    GENOTYPE_LENGTH,
    MIN_MUTATIONS,
    MAX_MUTATIONS,
    STARTING_ANIMALS,
    STARTING_PLANTS,
    MIN_REPRODUCTION_ENERGY,
    REPRODUCTION_ENERGY_COST,
    STARTING_ENERGY,
    DAILY_ENERGY_COST,
    DAILY_PLANTS_GROWTH,
    ENERGY_FROM_PLANT
}
